export const metadata = {
    title: 'Shop | LWSKart',
    description: 'Generated by Shop Page LWSkart app'
};

const ShopPage = () => {
    return <div>This is Shop Page</div>;
};

export default ShopPage;
