import PageLeftHanding from '@/app/components/Shared/PageLeftHading/PageLeftHanding';
import Image from 'next/image';
import LeftMenu from './_components/LeftMenu';
import product1 from '@/assets/images/products/product1.jpg';
import Link from 'next/link';

export const metadata = {
    title: 'Shop | LWSKart',
    description: 'Generated by Shop Page LWSkart app'
};

const ShopPage = ({ searchParams }) => {
    return (
        <>
            <PageLeftHanding>Shop</PageLeftHanding>

            <div className='container grid items-start grid-cols-1 gap-6 pb-8 lg:pt-4 md:pb-16 lg:grid-cols-4'>
                <LeftMenu />
                <div className='grid grid-cols-1 gap-6 sm:grid-cols-2 xl:grid-cols-3 lg:col-span-3'>
                    {/* Product cards */}
                    <div className='overflow-hidden bg-white rounded shadow cursor-pointer group'>
                        <Link href={`/product`} className='relative'>
                            <Image
                                className='w-full'
                                src={product1}
                                alt='product 1'
                                width={400}
                                height={400}
                            />
                            <div className='absolute inset-0 flex items-center justify-center gap-2 transition bg-black opacity-0 bg-opacity-40 group-hover:opacity-100'></div>
                        </Link>
                        <div className='px-4 pt-4 pb-3'>
                            <h4 className='mb-2 text-xl font-medium text-gray-800 uppercase transition hover:text-primary'>
                                Guyer Chair
                            </h4>
                            <div className='flex items-baseline mb-1 space-x-2'>
                                <p className='text-xl font-semibold text-primary'>$45.00</p>
                                <p className='text-sm text-gray-400 line-through'>$55.90</p>
                            </div>
                        </div>
                        <button className='flex items-center justify-center w-full gap-2 py-1 font-medium text-white uppercase transition-colors border rounded bg-primary border-primary hover:bg-transparent hover:text-primary disabled:cursor-not-allowed disabled:bg-gray-400/20 disabled:text-gray-500/70 disabled:border-gray-400/25'>
                            Add To Cart
                        </button>
                    </div>
                    <div className='overflow-hidden bg-white rounded shadow cursor-pointer group'>
                        <Link href={`/product`} className='relative'>
                            <Image src={product1} alt='product 1' width={400} height={400} />
                            <div className='absolute inset-0 flex items-center justify-center gap-2 transition bg-black opacity-0 bg-opacity-40 group-hover:opacity-100'></div>
                        </Link>
                        <div className='px-4 pt-4 pb-3'>
                            <h4 className='mb-2 text-xl font-medium text-gray-800 uppercase transition hover:text-primary'>
                                Guyer Chair
                            </h4>
                            <div className='flex items-baseline mb-1 space-x-2'>
                                <p className='text-xl font-semibold text-primary'>$45.00</p>
                                <p className='text-sm text-gray-400 line-through'>$55.90</p>
                            </div>
                        </div>
                        <button className='flex items-center justify-center w-full gap-2 py-1 font-medium text-white uppercase transition-colors border rounded bg-primary border-primary hover:bg-transparent hover:text-primary disabled:cursor-not-allowed disabled:bg-gray-400/20 disabled:text-gray-500/70 disabled:border-gray-400/25'>
                            Add To Cart
                        </button>
                    </div>
                    <div className='overflow-hidden bg-white rounded shadow cursor-pointer group'>
                        <Link href={`/product`} className='relative'>
                            <Image src={product1} alt='product 1' width={400} height={400} />
                            <div className='absolute inset-0 flex items-center justify-center gap-2 transition bg-black opacity-0 bg-opacity-40 group-hover:opacity-100'></div>
                        </Link>
                        <div className='px-4 pt-4 pb-3'>
                            <h4 className='mb-2 text-xl font-medium text-gray-800 uppercase transition hover:text-primary'>
                                Guyer Chair
                            </h4>
                            <div className='flex items-baseline mb-1 space-x-2'>
                                <p className='text-xl font-semibold text-primary'>$45.00</p>
                                <p className='text-sm text-gray-400 line-through'>$55.90</p>
                            </div>
                        </div>
                        <button className='flex items-center justify-center w-full gap-2 py-1 font-medium text-white uppercase transition-colors border rounded bg-primary border-primary hover:bg-transparent hover:text-primary disabled:cursor-not-allowed disabled:bg-gray-400/20 disabled:text-gray-500/70 disabled:border-gray-400/25'>
                            Add To Cart
                        </button>
                    </div>
                    <div className='overflow-hidden bg-white rounded shadow cursor-pointer group'>
                        <Link href={`/product`} className='relative'>
                            <Image src={product1} alt='product 1' width={400} height={400} />
                            <div className='absolute inset-0 flex items-center justify-center gap-2 transition bg-black opacity-0 bg-opacity-40 group-hover:opacity-100'></div>
                        </Link>
                        <div className='px-4 pt-4 pb-3'>
                            <h4 className='mb-2 text-xl font-medium text-gray-800 uppercase transition hover:text-primary'>
                                Guyer Chair
                            </h4>
                            <div className='flex items-baseline mb-1 space-x-2'>
                                <p className='text-xl font-semibold text-primary'>$45.00</p>
                                <p className='text-sm text-gray-400 line-through'>$55.90</p>
                            </div>
                        </div>
                        <button className='flex items-center justify-center w-full gap-2 py-1 font-medium text-white uppercase transition-colors border rounded bg-primary border-primary hover:bg-transparent hover:text-primary disabled:cursor-not-allowed disabled:bg-gray-400/20 disabled:text-gray-500/70 disabled:border-gray-400/25'>
                            Add To Cart
                        </button>
                    </div>
                    {/* End of product card */}
                </div>
            </div>
        </>
    );
};

export default ShopPage;
