import PageLeftHanding from '@/app/components/Shared/PageLeftHading/PageLeftHanding';
import getUserCarts from '@/app/server/getData/cart/getUserCarts';
import CheckOutForm from './_component/CheckOutForm';

export const metadata = {
    title: 'Checkout | LWSKart',
    description: 'Generated by Checkout Page LWSkart app'
};

const CheckOutPage = async () => {
    const carts = await getUserCarts();
    const cartsData = JSON.parse(carts);

    return (
        <>
            {/* CheckOut Page Hading */}
            <PageLeftHanding>Checkout</PageLeftHanding>
            {/* CheckOut Page Hading */}

            {/* CheckOut Form */}
            <CheckOutForm cartsData={cartsData} />
        </>
    );
};

export default CheckOutPage;
