import PageLeftHanding from '@/app/components/Shared/PageLeftHading/PageLeftHanding';
import FormControl from './_component/FormControl';
import getUserCarts from '@/app/server/getData/cart/getUserCarts';
import OrderSummary from './_component/OrderSummary';

export const metadata = {
    title: 'Checkout | LWSKart',
    description: 'Generated by Checkout Page LWSkart app'
};

const CheckOutPage = async () => {
    const carts = await getUserCarts();
    const cartsData = JSON.parse(carts);

    // Form control disabled
    const disabled = cartsData.length > 0 ? false : true;

    return (
        <>
            {/* CheckOut Page Hading */}
            <PageLeftHanding>Checkout</PageLeftHanding>
            {/* CheckOut Page Hading */}

            {/* CheckOut Form */}
            <form className='container grid items-start grid-cols-1 gap-6 pt-4 pb-16 lg:grid-cols-12'>
                <div className='p-4 border border-gray-200 rounded md:col-span-2 lg:col-span-8'>
                    <h3 className='mb-4 text-lg font-medium capitalize'>Checkout</h3>
                    <div className='space-y-4'>
                        <div className='grid grid-cols-1 gap-4 lg:grid-cols-2'>
                            <FormControl
                                disabled={disabled}
                                id='first-name'
                                label='First Name'
                                required={true}
                            />
                            <FormControl
                                disabled={disabled}
                                id='last-name'
                                label='Last Name'
                                required={true}
                            />
                        </div>
                        <FormControl id='email' label='Email address' />
                        <FormControl id='phone' label='Phone number' />
                        <FormControl id='company' label='Company' />
                        <FormControl id='region' label='Country/Region' />
                        <FormControl id='address' label='Street address' />
                        <FormControl id='city' label='City' />
                    </div>
                </div>

                {/* Order Summary */}
                <OrderSummary cartsData={cartsData} />
            </form>
        </>
    );
};

export default CheckOutPage;
