import { Inter } from 'next/font/google';
import './globals.css';
import Header from './components/Shared/Header/Header';
import Footer from './components/Shared/Footer/Footer';
import Navbar from './components/Shared/Navbar/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'LWSKart',
    description: 'Generated by LWSkart app'
};

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <Header />
                <Navbar />
                {children}
                <Footer />
            </body>
        </html>
    );
}
